### PR TITLE
frontend: Migrate to use the new MetaMask API 

### LINKED ISSUE #338: MetaMask is not working anymore
MetaMask introduced a breaking change which breaks our integration. The `window.web3` object isn't provided anymore. See [this](https://docs.metamask.io/guide/provider-migration.html) for further information.

### PR DESCRIPTION
**Pull request by manuelwedler**
Fixes #338 

MetaMask removed the injected `window.web3` object recently, which we relied on. This broke our integration of MetaMask.

MetaMask should now be used through the `window.ethereum` API, which is specified by EIP 1193. This PR migrates the frontend to use this API to make the transaction request. The only place where we send a transaction from the frontend is for funding the user account.

This uses a small library (`@metamask/detect-provider`) to detect the rpc provider as recommended by MetaMask.

### CODE REVIEW

File: resources/static/js/account.js [hunk 1]
```diff
@@ -86,72 +94,90 @@ function showRamp() {
...
-    if (chain_id != required_chain_id) {
-      let current_chain_name = CHAIN_ID_MAPPING[chain_id];
-      let required_chain_name = CHAIN_ID_MAPPING[required_chain_id];
-      alert(
-        `Web3 Browser connected to ${current_chain_name}, please change to ${required_chain_name}.`
-      );
-    }
-  });
+  const requiredChainID = CHAIN_ID;
+  const currentChainID = parseInt(await provider.request({ method: 'eth_chainId' }), 16);
```
Comment (ezdac) [inline resources/static/js/account.js:98]: Before there was console error logging. Shouldn't the await call be wrapped around a try/catch block?

File: resources/static/js/account.js [hunk 2]
```diff
@@ -86,72 +94,90 @@ function showRamp() {
...
 
-function makeWeb3Transaction(w3, transaction_data) {
-  w3.eth.sendTransaction(transaction_data, function (error, result) {
-    if (result) {
-      // result is the transaction hash
-      trackTransaction(result, CONFIGURATION_FILE_NAME);
+async function connectWeb3() {
+  let accounts = [];
+  try {
+    accounts = await provider.request({ method: 'eth_accounts' });
```
Comment (ezdac) [inline resources/static/js/account.js:113]: Should this even be called before calling `eth_requestAccounts`, or will this fail all the time anyways?
I read it that way that `eth_requestAccounts` **MAY eventually** trigger the UI-element - meaning that this is only the case for the first access-request? I could be wrong - so I'm mainly just curious.

File: resources/static/js/account.js [hunk 3]
```diff
@@ -86,72 +94,90 @@ function showRamp() {
...
-    web3.eth.defaultAccount;
-  let gasPrice;
+  const correctNetwork = await checkWeb3Network();
+  if (!correctNetwork) {
+    return;
+  }
 
+  const accounts = await connectWeb3();
+  if (accounts.length === 0) {
+    return;
```
Comment (ezdac) [inline resources/static/js/account.js:149]: Can this also be the case when the `eth_requestAccounts` was successful but the list is still empty?
Would this scenario need communication with the user?

**Review by ezdac — CHANGES_REQUESTED** [review]
Looks good as far as I can tell. Added some questions, but most of them are out of curiosity.
Please ignore if the answer is obvious.
I believe the 1 missing error handling should be implemented though.

File: resources/static/js/account.js (hunk 1 above)
Comment (manuelwedler) [reply resources/static/js/account.js:98]: Good point! Thanks.

File: resources/static/js/account.js (hunk 2 above)
Comment (manuelwedler) [reply resources/static/js/account.js:113]: The user may already have given the allowance to access the accounts, when the button is clicked. For example in case the button is clicked a second time after canceling the first transaction. 
In my understanding, every call to `eth_requestAccounts` may trigger a user interface, depending on the RPC Provider. Since this is not the case with MetaMask, I think we can just use the call to `eth_requestAccounts`.

File: resources/static/js/account.js (hunk 3 above)
Comment (manuelwedler) [reply resources/static/js/account.js:149]: From the EIP 1102:
> Browsers MUST include at least one account if the eth_requestAccounts promise is resolved.

The list will only be empty if there was an error and in this case we show an alert.

File: resources/static/js/account.js (hunk 2 above)
Comment (ezdac) [reply resources/static/js/account.js]: Ok - I couldn't find anything about `eth_accounts` being unlocked by the `eth_requestAccounts` as well, 
and the example code from the metamask docs was using `eth_requestAccounts` just before a transaction.

**Review by ezdac — APPROVED** [review]
Looks good
